swagger: "2.0"
info:
  version: 1.0.0
  title: noa-api
  description: Notice of Acting
basePath: /api/v1
tags:
  - name: NoA
    description: NoA endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  NoaRequestBody:
    type: object
    title: noaRequest
    required:
      - requester
      - requestType
      - caseJurisdiction
      - caseType
      - originatorEmail
      - originatorIdam
      - contact
    properties:
      requester:
        type: object
        example: no_stress
      requestType: 
        type: string
        example: no_stress
      caseJurisdiction: 
        type: string
        example: no_stress
      caseType: 
        type: string
        example: no_stress
      originatorEmail: 
        type: string
        example: no_stress
      originatorIdam: 
        type: string
        example: no_stress
      contact:
        type: object
        example: no_stress

paths:

  /noa/create/{caseid}/{email}:
    post:
      tags:
        - create
      description: Validate and create NoA, send confirmation request
      parameters:
        - name: caseid
          in: path
          description: Id of case
          required: true
          type: string
        - name: email
          in: path
          description: email of appellant
          required: true
          type: string
        - name: noaRequest
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/NoaRequestBody"
      responses:
        200:
          description: Request sent
        404:
          description: Request not sent

  /noa/confirm/{uuid}:
    post:
      tags:
        - confirm
      description: Confirm NoA, send confirmation success
      parameters:
        - name: uuid
          in: path
          description: Id of case
          required: true
          type: string
      responses:
        200:
          description: Success sent
        404:
          description: Success not sent

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification